/**
 * Writes lib/wrapper-errors.ts from the oracle fixture's `allErrors` (every PercolatorError
 * variant by name, ordinals by rustc). Run after regenerating rust-p3-final.json:
 *   npx tsx scripts/limits-parity/p3-final/gen-wrapper-errors.ts
 * __tests__/lib/limits/p3-final-parity.test.ts pins the file to the fixture.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(__dirname, "..", "..", "..");
const fx = JSON.parse(readFileSync(join(root, "__tests__/fixtures/limits/rust-p3-final.json"), "utf8")) as {
  p3Sha: string;
  allErrors: Record<string, number>;
};
const rows = Object.entries(fx.allErrors).sort((a, b) => a[1] - b[1]);
const body = rows.map(([n, v]) => `  ${n}: ${v},`).join("\n");
writeFileSync(
  join(root, "lib/wrapper-errors.ts"),
  `/**
 * GENERATED by scripts/limits-parity/p3-final/gen-wrapper-errors.ts from the oracle fixture
 * (__tests__/fixtures/limits/rust-p3-final.json \`allErrors\`, wrapper ${fx.p3Sha.slice(0, 8)}).
 * Every wrapper PercolatorError ordinal the app maps comes from here; do not edit by hand.
 */
export const WRAPPER_ERR = {
${body}
} as const;

export type WrapperErrorName = keyof typeof WRAPPER_ERR;
`,
);
console.log(`wrote ${rows.length} wrapper error codes`);
